name: Deploy Dev Branch
on:
  push:
    branches:
      - Development

permissions:
  issues: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{secrets.AZURESTATICWEBAPPNODEVERSION}}
          cache: "npm"
      - name: npm install and npm build
        run: |
          npm install
          npm run build
      - name: npm run lint
        run: npm run lint
      - name: npm test
        run: npm run test -- --coverage 2>&1 | tee test_run_output.txt
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURESUBPRODWEBAPPAPITOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: /build
          skip_app_build: true
